Upgrade to debian12 and rundeck4.17.4
panubo/docker-rundeck pull request #8
Opened 2024-01-18 11:20 UTC by chaopanubo

Andrew's PR for bug config had been merged by the code owner.

2024-01-18 23:35 UTC, macropin requested changes
Rundeck does not support JDK17. Only Java 11 is supported. Ref: https://docs.rundeck.com/docs/administration/install/system-requirements.html

2024-01-26 07:47 UTC, macropin commented on Dockerfile
>    ;
Please pin this install to a specific release. eg `git checkout 1.25.3`

2024-01-28 21:49 UTC, trnubo commented on install-openjdk-11.sh
> +echo "deb http://deb.debian.org/debian bullseye main" > /etc/apt/sources.list.d/openjdk-11.list
What is this script doing? Are we just installing the debian 11 (bullseye) packing on debian 12 (bookworm)? This is probably not safe.

2024-01-29 04:17 UTC, trnubo commented on install-openjdk-11.sh
> +echo "deb http://deb.debian.org/debian bullseye main" > /etc/apt/sources.list.d/openjdk-11.list
```diff
diff --git a/Dockerfile b/Dockerfile
index d0600dd..793c60f 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -12,10 +12,14 @@ RUN set -x \
   ;

 # Install JDK11
-COPY install-openjdk-11.sh /
 RUN set -x \
   && mkdir /etc/ssl/certs/java/ \
-  && /install-openjdk-11.sh \
+  && wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | apt-key add - \
+  && echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list \
+  && apt-get update \
+  && apt-get install --no-install-recommends --no-install-suggests -y temurin-11-jdk \
+  && apt-get clean \
+  && rm -rf /var/lib/apt/lists/* \
   ;

 # Install Google Cloud SDK
```

@macropin what do you think about using adoptium instead? I'll push this to the branch/PR if you agree.

https://adoptium.net/blog/2021/12/eclipse-temurin-linux-installers-available/

2024-01-29 04:19 UTC, trnubo commented on install-tools.sh
> +
Add Helm 3.13.x (what ever the latest 3.13 is)

2024-01-29 04:20 UTC, trnubo commented on install-tools.sh
>  install_helm 3.11.2
Upgrade to 3.11.3

2024-01-29 04:22 UTC, trnubo commented on install-tools.sh
>  install_kubectl 1.26.3
Upgrade to the latest 1.24.x, 1.25.x and 1.26.x releases

Add 1.27 and 1.28 latest releases

2024-04-24 00:38 UTC, trnubo commented
Please update this PR.

We want to:
- Stick to debian:11 upstream
- Install AWS CLI v1 via pip instead of apt-get
- Stick to rundeck 4.x versions
- Check all tools are upto date
- Include k8s 1.29
- Include helm 3.14.x

2024-04-26 04:17 UTC, macropin requested changes
Other than that whitespace change. LGTM

2024-04-26 04:17 UTC, macropin commented on Dockerfile
> +
unnecessary whitespace

2024-04-26 04:42 UTC, chaopanubo commented on Dockerfile
> +
Fixed.

2024-04-26 04:42 UTC, chaopanubo commented
> Other than that whitespace change. LGTM

Thank you, Andrew.

2024-04-26 04:47 UTC, merged